### ISSUE TITLE
joke references

### ISSUE THREAD

**Issue by denkorzh** [vita-epfl/collaborative-gan-sampling#1]
Please pay your attention to the following fact: subsection 2.4 of your paper https://arxiv.org/pdf/1902.00813v1.pdf cites jokes, not academic papers:

LeCun, Y. Generative Collaborative Networks. Twitter, 2016. URL https://twitter.com/boredyannlecun/status/791115429766766592?lang=en

Albanie, S., Ehrhardt, S., and Henriques, J. F. Stopping gan violence: Generative unadversarial networks. arXiv preprint arXiv:1703.02528, 2017.

**Comment by YuejiangLIU** [comment]
> Please pay your attention to the following fact: subsection 2.4 of your paper https://arxiv.org/pdf/1902.00813v1.pdf cites jokes, not academic papers:
> 
> LeCun, Y. Generative Collaborative Networks. Twitter, 2016. URL https://twitter.com/boredyannlecun/status/791115429766766592?lang=en
> 
> Albanie, S., Ehrhardt, S., and Henriques, J. F. Stopping gan violence: Generative unadversarial networks. arXiv preprint arXiv:1703.02528, 2017.

Thanks for your comments. Yes, we know they are jokes. But our work was originally inspired by these interesting jokes, so we cited them.
