### ISSUE TITLE
Http 404 response for wget command

### ISSUE THREAD

**Issue by efak** [vita-epfl/collaborative-gan-sampling#2]
The command below results in HTTP 404 response:
`wget https://github.com/tensorflow/models/raw/master/research/gan/mnist/data/classify_mnist_graph_def.pb -P external/`

**Comment by YuejiangLIU** [comment]
Thanks for pointing it out. The link to the file 'classify_mnist_graph_def.pb' in the tensorflow repo was changed. 
I have added this file directly. No need to download it from an external link now.
