### ISSUE TITLE
Ask for your help

### ISSUE THREAD

**Issue by Taraing** [vita-epfl/collaborative-gan-sampling#3]
Hi!  I use social gan to predict my our data,but it always told me   File "/home/wyx/sgan-master/sgan/data/trajectories.py", line 336, in __init__
    curr_seq[_idx, :, pad_front:pad_end] = curr_ped_seq  # curr_seq(3*2*20)
ValueError: could not broadcast input array from shape (2,6) into shape (2,20).I consider the reason is that the change of the number of people in each frame of video,But i am not sure and can't resolve this problem.Please help me!!Thanks very much!

**Comment by YuejiangLIU** [comment]
Sorry for answering late. As this repo is not much related to social gan, I'm closing it now. Please free feel to drop me an email if you'd like to discuss something outside the scope of this work.
